from django.contrib.auth.models import User
from userApp.models import Cliente
from mainApp.models import Pizza, Pedido, Ingrediente, Carrito, IngredientePizza

u1 = User.objects.create_user(username='user1', password='contraseña', first_name='Lolo', last_name='Manolo')
c1 = Cliente(user=u1, telefono=123456, direccion='Calle Falsa 123')
c1.save()

u2 = User.objects.create_user(username='user2', password='contraseña', first_name='Choro', last_name='Mota')
c2 = Cliente(user=u2, telefono=213456, direccion='Calle Falsa 234')
c2.save()

u3 = User.objects.create_user(username='user3', password='contraseña', first_name='Choro', last_name='Naco')
c3 = Cliente(user=u3, telefono=213457, direccion='Calle Falsa 235')
c3.save()

u4 = User.objects.create_user(username='user4', password='contraseña', first_name='Rosa', last_name='Espinoza')
c4 = Cliente(user=u4, telefono=987123, direccion='Calle Falsa 987')
c4.save()

p1 = Pizza(nombre='Pepperoni', descripcion='Sabrosa')
p2 = Pizza(nombre='Napolitana', descripcion='Sabrosa')
p3 = Pizza(nombre='Pollo BBQ', descripcion='Sabrosa')
p4 = Pizza(nombre='Selección', descripcion='Sabrosa')
p1.save()
p2.save()
p3.save()
p4.save()

i1 = Ingrediente(nombre='Mozarella')
i2 = Ingrediente(nombre='Pepperoni')
i3 = Ingrediente(nombre='Tomate')
i4 = Ingrediente(nombre='Salsa BBQ')
i5 = Ingrediente(nombre='Pollo')
i6 = Ingrediente(nombre='Cebolla')
i7 = Ingrediente(nombre='Champiñones')
i8 = Ingrediente(nombre='Pimentón')
i1.save()
i2.save()
i3.save()
i4.save()
i5.save()
i6.save()
i7.save()
i8.save()

ip1 = IngredientePizza(pizza=p1, ingrediente=i1)
ip2 = IngredientePizza(pizza=p1, ingrediente=i2)
ip3 = IngredientePizza(pizza=p2, ingrediente=i1)
ip4 = IngredientePizza(pizza=p2, ingrediente=i3)
ip5 = IngredientePizza(pizza=p3, ingrediente=i4)
ip6 = IngredientePizza(pizza=p3, ingrediente=i1)
ip7 = IngredientePizza(pizza=p3, ingrediente=i5)
ip8 = IngredientePizza(pizza=p3, ingrediente=i6)
ip9 = IngredientePizza(pizza=p4, ingrediente=i1)
ip10 = IngredientePizza(pizza=p4, ingrediente=i7)
ip11 = IngredientePizza(pizza=p4, ingrediente=i2)
ip12 = IngredientePizza(pizza=p4, ingrediente=i8)
ip1.save()
ip2.save()
ip3.save()
ip4.save()
ip5.save()
ip6.save()
ip7.save()
ip8.save()
ip9.save()
ip10.save()
ip11.save()
ip12.save()

o1 = Pedido(fechahora='2021-02-01 14:00', cliente=c1)
o2 = Pedido(fechahora='2021-02-03 14:00', cliente=c2)
o3 = Pedido(fechahora='2021-02-04 14:00', cliente=c2)
o4 = Pedido(fechahora='2021-01-12 14:00', cliente=c3)
o5 = Pedido(fechahora='2021-02-13 14:00', cliente=c3)
o6 = Pedido(fechahora='2021-02-15 14:00', cliente=c3)
o7 = Pedido(fechahora='2021-05-01 14:00', cliente=c3)
o8 = Pedido(fechahora='2021-06-01 14:00', cliente=c4)
o9 = Pedido(fechahora='2021-06-02 14:00', cliente=c4)
o10 = Pedido(fechahora='2021-06-03 14:00', cliente=c4)
o11 = Pedido(fechahora='2021-06-04 14:00', cliente=c4)
o1.save()
o2.save()
o3.save()
o4.save()
o5.save()
o6.save()
o7.save()
o8.save()
o9.save()
o10.save()
o11.save()

k1 = Carrito(pedido=o1, pizza=p1, cantidad=1, tamano='L')
k2 = Carrito(pedido=o2, pizza=p2, cantidad=1, tamano='XL')
k3 = Carrito(pedido=o2, pizza=p4, cantidad=2, tamano='XL')
k4 = Carrito(pedido=o3, pizza=p1, cantidad=3, tamano='L')
k5 = Carrito(pedido=o3, pizza=p2, cantidad=1, tamano='L')
k6 = Carrito(pedido=o3, pizza=p3, cantidad=1, tamano='L')
k7 = Carrito(pedido=o3, pizza=p4, cantidad=1, tamano='L')
k8 = Carrito(pedido=o4, pizza=p1, cantidad=2, tamano='M')
k9 = Carrito(pedido=o5, pizza=p3, cantidad=1, tamano='M')
k10 = Carrito(pedido=o5, pizza=p4, cantidad=1, tamano='M')
k11 = Carrito(pedido=o6, pizza=p2, cantidad=2, tamano='L')
k12 = Carrito(pedido=o7, pizza=p3, cantidad=1, tamano='XL')
k13 = Carrito(pedido=o8, pizza=p1, cantidad=1, tamano='L')
k14 = Carrito(pedido=o9, pizza=p2, cantidad=2, tamano='XL')
k15 = Carrito(pedido=o10, pizza=p4, cantidad=1, tamano='L')
k16 = Carrito(pedido=o11, pizza=p3, cantidad=1, tamano='M')
k1.save()
k2.save()
k3.save()
k4.save()
k5.save()
k6.save()
k7.save()
k8.save()
k9.save()
k10.save()
k11.save()
k12.save()
k13.save()
k14.save()
k15.save()
k16.save()
