# Generated by Django 3.2 on 2021-06-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proveedor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(upload_to='pizza-img/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientePizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ingrediente')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('tamano', models.CharField(choices=[('M', 'Mediana'), ('L', 'Familiar'), ('XL', 'XL')], max_length=15)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pizza')),
            ],
        ),
    ]
